apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deploy1
  labels:
    app  : my-k8s-application1
    env  : prod
    owner: KirillLushnikov
spec:
  replicas: 2
  selector:
    matchLabels:
      project: k8s1
  template:
    metadata:
      labels:
        project: k8s1
    spec:
      containers:
        - name : k8s-grafana1
          image: grafana/grafana:main
          ports:
           - containerPort: 3000
