apiVersion: v1
kind: Service
metadata:
  name: my-service1
  labels:
    env  : prod
    owner: KirillLushnikov
spec:
  selector:
    project: k8s1
  ports:
    - name      : app1-listener
      protocol  : TCP
      port      : 3000
      targetPort: 3000
  type: LoadBalancer
