apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy
  labels:
    app  : {{ .Release.Name }}-application
    env  : prod
    owner: KirillLushnikov
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: {{ .Release.Name }}
  template:
    metadata:
      labels:
        project: {{ .Release.Name }}
    spec:
      containers:
        - name : {{ .Release.Name }}-grafana
          image: {{ .Values.container.image }}
          ports:
           - containerPort: 3000
