apiVersion: v1
kind: Service
metadata:
  name: my-service2
  labels:
    env  : prod
    owner: KirillLushnikov
spec:
  selector:
    project: k8s2
  ports:
    - name      : app-listener2
      protocol  : TCP
      port      : 3000
      targetPort: 3000
  type: LoadBalancer
